name: server_code_lab
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Code-lab server sample.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  browser: '>=0.10.0+2 <0.11.0'
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.11.1 <0.12.0'
  logging_handlers: '>=0.8.0 <0.9.0'
  rpc: '>=0.3.0 <0.4.0'
