name: components_codelab
description: An AngularDart app that simulates a lottery
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  intl: ^0.14.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
      Random: 'dart:math'
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
